name: test-on-gnu-linux
on: [push, pull_request]
jobs:
  make-test:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color

    strategy:
      #fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
        os: [ubuntu-20.04, ubuntu-18.04]
        # https://hub.docker.com/_/perl
        perl-version: [latest, 5.30, 5.26, 5.8.9]

    container:
      image: perl:${{ matrix.perl-version }}

    name: Build on ${{ matrix.os }} with Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
            perl -V
            apt install -y libreadline-dev
      - name: Run make test
        run: |
            perl Makefile.PL
            make
            make test
